<a href="https://colab.research.google.com/github/thekhushikhurana-sudo/ForKidsByKids/blob/main/mod2_numpy_fundamentals/3_manipulating_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Fundamentals: Manipulating Matrices
Please follow the instructions and uncomment the skeleton code as necessary.

This assignment is due in addition to the small group assignment before the next class

In [1]:
import numpy as np

In [2]:
# Create a 3x3x3 np.array
my_array = [[[1]],[[2]],[[3]]] * np.ones((3,3,3))
print(my_array)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


## Multidimensional Indexing

### Q.1 Print the value `2.0` from `my_array` using its index

In [9]:
print(my_array[1][0][0])

2.0


**bold text**#### Q.2 Use multidimensional slicing to print a 3x3 array that contains *all* values of `2` from `my_array`.

In [12]:
print(my_array[1, :, :])

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


#### Q.3 Use multidimensional slicing to add `5` to every other element in `my_array` such that `print(new_array)` outputs

```python
[[[6. 1. 6.]
  [1. 6. 1.]
  [6. 1. 6.]]

 [[7. 2. 7.]
  [2. 7. 2.]
  [7. 2. 7.]]

 [[8. 3. 8.]
  [3. 8. 3.]
  [8. 3. 8.]]]
```

In [5]:
# create a copy of my_array named new_array
my_array = [[[1]],[[2]],[[3]]] * np.ones((3,3,3))
new_array = my_array

# add 5 to every other element
# new_array[ <YOUR ANSWER HERE> ] += 5         # add 5 to the corner elements
# new_array[ <YOUR ANSWER HERE> ] += 5         # add 5 to the center elements
#print(new_array)


## Reshaping Matrices

#### Please refer to your notes on the `transpose`, `reshape`, and `flatten` methods to answer questions 4-6.

#### Q.4 Create a 1D array from on `my_array`.

In [6]:
# my_1d_array = <YOUR ANSWER HERE>
# print(my_1d_array)

#### Q.5 Create a 2D array from `my_array` that has 3 rows and 9 columns

In [7]:
#my_2d_array = <YOUR ANSWER HERE>
#print(my_2d_array)

#### Q.6 Create a new 3D array from `my_array` so that each 3x3 sub-array has at least one row with the values `[1, 2, 3]`.

In [29]:
#transposed_array = <YOUR ANSWER HERE>
#print(transposed_array)

In [32]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
b = a.reshape(4, 4)
c = a.reshape(2, 2, 4)
d = a.reshape(2, 2, 2, 2)

print(d[0, 1, 0, 1])
print(d[0, 1, 0, 0])
print(d[1, 0, 0, 0])

5
4
8
